version: '3.7'

services:
  back:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /staticfiles:/app/staticfiles
      - ${PWD}/db.sqlite3:/app/db.sqlite3
    links:
      - db-postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
