version: '3.7'

services:
  back:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /staticfiles:/app/staticfiles
      - ${PWD}/db.sqlite3:/app/db.sqlite3
      - ./media/:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
