# Generated by Django 4.1.7 on 2023-06-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movierating_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movierating',
            options={'ordering': ['-id']},
        ),
    ]
